baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Tutorials for quanteda"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
  editURL = "https://github.com/quanteda/quanteda_tutorials/tree/master/content/"
  description = "Introduction to quantitative text analysis using quanteda"
  author = "Kenneth Benoit"
  showVisitedLinks = true
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
# title = "Tutorials for quanteda"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/quanteda/quanteda"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Documentation"
identifier = "hugodoc"
url = "http://docs.quanteda.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-home'></i> Website"
identifier = "hugodoc"
url = "http://quanteda.io/"
weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

# [Languages.fr]
# title = "Documentation du thème Hugo Learn"
# weight = 2
# languageName = "Français"

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-github'></i> Repo Github"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Crédits"
# url = "/credits"
# weight = 30
